default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: matsumoto_development

test:
  <<: *default
  database: matsumoto_test


production:
  <<: *default
  database: matsumoto_production
  username: matsumoto
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
